apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-ezpd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-ezpd@sha256:cdc572b5c78a12e2785dcb0abf42d1e6fe9714bc27f89153bd2fe31abd8bdea6
        name: my-nodejs
        resources: {}
status: {}
